openapi: 3.0.3
info:
  title: Product Pricing Service
  version: 1.0.0

paths:
  /api/v1/product-price:
    get:
      summary: Search applicable price
      tags:
        - ProductPrice
      description: Returns the applicable price for a product, brand and application date.
      operationId: getProductPrice
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: applicationDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPriceResponse'
        '404':
          description: No applicable price found

components:
  schemas:
    ProductPriceResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
          format: int64
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
        currency:
          type: string
          minLength: 3
          maxLength: 3
