openapi: 3.0.3
info:
  title: Product Pricing Service
  version: 1.0.0

paths:
  /prices/search:
    post:
      summary: Search applicable price
      description: Returns the applicable price for a product, brand and application date.
      operationId: searchPrices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriceRequest'
      responses:
        '200':
          description: Price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '404':
          description: No applicable price found

components:
  schemas:
    PriceRequest:
      type: object
      required:
        - applicationDate
        - productId
        - brandId
      properties:
        applicationDate:
          type: string
          format: date-time
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceList:
          type: integer
          format: int64
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
        currency:
          type: string
          minLength: 3
          maxLength: 3
